<?php
// opne ai api
ob_start();
add_action( 'wp_ajax_nopriv_open_ai_ajax', 'open_ai_ajax' );
add_action( 'wp_ajax_open_ai_ajax', 'open_ai_ajax' );


function open_ai_image_ajax(){

    
    if(isset($_POST['aidata']) && !empty($_POST['aidata'])){
    $message = $_POST['aidata'];
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://api.openai.com/v1/images/generations');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n    \"prompt\": \"$message\",\n    \"n\": 1,\n    \"size\": \"1024x1024\"\n  }");

    $headers = array();
    $headers[] = 'Content-Type: application/json';
    $headers[] = 'Authorization: Bearer '.AI_CHATBOT_API_KEY;
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);

    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);

$openai_data = json_decode($result);
$src = $openai_data->data[0]->url;
// echo "<pre>";
// print_r($openai_data);
// echo "</pre>";
// echo "<h3 class='ai-style'>".$src.'</h3>';

echo "<img width='400px' src='".$src."' />";

}
die();
}


//create function with an exception
function checkNum($number) {
  if($number>1) {
    throw new Exception("Invaild Authentication and Request Error.");
  }
  return true;
}

function ai_chatbot_message($content){
			
return '<article class="msg-container msg-remote" id="msg-0"><div class="msg-box"><div class="flr"><div class="messages"><p class="msg" id="msg-1">'.$content.'</p></div><span class="timestamp"><span class="username">AI bot</span>&bull;<span class="posttime">Now</span></span></div><img class="user-img" id="user-0" src="'.AI_CHATBOT_IMG_BOAT.'" /></div><audio controls autoplay audio style="display:none;"> <source src="'.AI_CHATBOT_AI_AUDIO.'"  type="audio/mpeg"> </audio></article></article>';


// <p class='ai-style'>".$openai_data->choices[0]->message->content.'</p>';
// echo 'prompt_tokens = '. $openai_data->usage->prompt_tokens.'<br>';
// echo 'completion_tokens = '. $openai_data->usage->completion_tokens.'<br>';
// echo 'total_tokens = '. $openai_data->usage->total_tokens.'<br>';
}


function open_ai_ajax(){

    
    if(isset($_POST['aidata']) && !empty($_POST['aidata'])){

    $message = $_POST['aidata'];
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://api.openai.com/v1/chat/completions');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n     \"model\": \"gpt-3.5-turbo\",\n     \"messages\": [{\"role\": \"user\", \"content\": \"$message\"}],\n     \"temperature\": 0.7\n   }");

    $headers = array();
    $headers[] = 'Content-Type: application/json';
    $headers[] = 'Authorization: Bearer '.AI_CHATBOT_API_KEY;
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);

    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);

$openai_data = json_decode($result);

$error = isset($openai_data->choices[0]->message->content)?true:2;
		
		
		//trigger exception in a "try" block
try { 
		checkNum($error);
  //If the exception is thrown, this text will not be shown
 echo ai_chatbot_message($openai_data->choices[0]->message->content);
}

//catch exception
catch(Exception $e) {
		echo "<article class='ai-cb-error-msg'>Message: " .$e->getMessage()."(".$openai_data->error->type.")</article>";
	
// 	echo "<pre>";
// print_r($openai_data->error->type);
// echo "</pre>";
}		

} // if isset close
die();
}

function open_ai_input(){
    echo "<h2>Open AI data</h2>";
    echo '<form method="post">
<ul class="wrapper">
    <li class="form-row">
      <label for="wurl">Generate AI Data</label>
      <input type="text" id="ai-data" name="ai-data" value="" class="regular-text"><br>
    </li>

    <li class="form-row">
    <input type="button" value="Generate" class="button button-primary" id="openai-data">
    </li>
  </ul>
</form>';

}




ob_end_clean();
